// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    def kotlin_major_version = '2.1.0'
    def kotlin_minor_version = '1.0.29'
    ext.kotlin_major_version  = kotlin_major_version
    ext.kotlin_minor_version  = kotlin_minor_version

    def lombok_plugin_version = "8.10"
    def lombok_version = '1.18.36'
    ext.lombok_plugin_version = lombok_plugin_version
    ext.lombok_version = lombok_version

    def kotlin_coroutines_version = "1.10.1"
    ext.kotlin_coroutines_version = kotlin_coroutines_version

    def androidx_core_version = "1.13.1" //1.15.0 requires compileSdk 35, which has breaking changes
    ext.androidx_core_version = androidx_core_version

    //ext.hilt_version = '2.44'
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.3'
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.github.jamorham:ReplaceTokenPreprocessor:1.5'
        classpath 'com.google.android.gms:oss-licenses-plugin:0.10.6'
        //classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${kotlin_major_version}"
        //classpath "io.freefair.gradle:lombok-plugin:${lombok_plugin_version}"
        //classpath "io.franzbecker.gradle-lombok:5.0.0"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
plugins {
    id 'java-library'
    //id 'maven-publish'
    id "io.freefair.lombok" version "${lombok_plugin_version}"
    id "org.jetbrains.kotlin.plugin.lombok" version "${kotlin_major_version}"
    //id 'io.franzbecker.gradle-lombok' version '5.0.0' apply false

    id "org.jetbrains.kotlin.android" version "${kotlin_major_version}" apply false
    id "org.jetbrains.kotlin.kapt" version "${kotlin_major_version}"   //iss apply false nec.>
    id 'com.google.devtools.ksp' version "${kotlin_major_version}-${kotlin_minor_version}" apply false
    id "com.github.spotbugs" version "6.0.26"
}
allprojects {
    tasks.withType(JavaCompile).configureEach {
        options.fork = true
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
if(JavaVersion.current() != JavaVersion.VERSION_17){
    throw new GradleException("This build must be run with java 17. Currently using ${JavaVersion.current() }")
}